"""empty message

Revision ID: 72508ef3db26
Revises: db6c509cb54c
Create Date: 2025-05-03 18:52:34.647644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72508ef3db26'
down_revision = 'db6c509cb54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favoritos_pperson_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['person_id'], ['id'])
        batch_op.drop_column('pperson_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pperson_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favoritos_pperson_id_fkey', 'people', ['pperson_id'], ['id'])
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
