"""empty message

Revision ID: ba209216a985
Revises: c891b7da20a6
Create Date: 2025-05-04 16:24:08.842443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba209216a985'
down_revision = 'c891b7da20a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint('favoritos_person_id_key', type_='unique')
        batch_op.drop_constraint('favoritos_planet_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.create_unique_constraint('favoritos_planet_id_key', ['planet_id'])
        batch_op.create_unique_constraint('favoritos_person_id_key', ['person_id'])

    # ### end Alembic commands ###
